apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-backend-route 
spec:
  gateways:
  - istio-system/istio-ingress-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /api/hello
    - uri:
        exact: /error
    route:
    - destination:
        host: backend-service
        subset: v1
        port:
          number: 5000
      weight: 10
    - destination:
        host: backend-service
        subset: v2
        port:
          number: 5000
      weight: 90
  - route:
    - destination:
        host: frontend-service
        port:
          number: 5050
