replicas: 1  # Single replica for Minikube
maxUnavailable: 1

antiAffinity: "soft"
# Allows co-location of pods, suitable for Minikube

esJavaOpts: "-Xms256m -Xmx256m"
# Moderate JVM heap size for development

createCert: false
# Disabled for simplicity in local setup

secret:
  enabled: true
  password: ""  # Simple password for development

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "400m"
    memory: "1Gi"
# Moderate resource allocation for local development

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 3Gi
# Smaller storage size, adequate for testing

# Use ClusterIP for Istio to manage external access
service:
  type: ClusterIP

# Ingress configuration for Istio
ingress:
  enabled: false  # Disable default ingress, we'll use Istio Gateway
  hosts:
    - host: elasticsearch.localhost
      paths:
        - path: /

# Prometheus config
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring  # Specify the namespace where Prometheus is running
    labels:
      release: prometheus  # Add this line to match Prometheus Operator's label selector
    interval: 10s  # Scrape interval, adjust as needed
    scrapeTimeout: 10s  # Scrape timeout, adjust as needed
