filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*-json.log

processors:
- add_kubernetes_metadata:
    in_cluster: true
    matchers:
    - logs_path:
        logs_path: "/var/lib/docker/containers/"

output.logstash:
  hosts: ["logstash:5044"]
