apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: logging
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [message] {
        json {
          source => "message"
          skip_on_invalid_json=> true
        }
      }
      if [kubernetes] {
        mutate {
          add_field => {
            "k8s_namespace" => "%{[kubernetes][namespace_name]}"
            "k8s_pod" => "%{[kubernetes][pod_name]}"
            "k8s_container" => "%{[kubernetes][container_name]}"
            "k8s_node" => "%{[kubernetes][node_name]}"
          }
        }
      }
      date {
        match => [ "timestamp" , "ISO8601" ]
        target => "@timestamp"
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      }
    }
