{
 "title": "Flask Application Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Global Cache Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cache_hits_total{job=\"backend\", pod=~\".*v2.*\"}[30m]) / \n  (\n    rate(cache_hits_total{job=\"backend\", pod=~\".*v2.*\"}[30m]) + \n    rate(cache_misses_total{job=\"backend\", pod=~\".*v2.*\"}[30m])\n  )) / (count(up{job=\"backend\",pod=~\".*v2.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Containers by Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod) (up{job=\"backend\", pod=~\".*v1.*\"}))",
     "legendFormat": "v1 Containers"
    },
    {
     "expr": "sum(count by (pod) (up{job=\"backend\", pod=~\".*v2.*\"}))",
     "legendFormat": "v2 Containers"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes))",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Request Process Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_time_seconds_sum[1m]) / rate(process_time_seconds_count[1m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(hello_requests_total[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(hello_response_time_seconds_sum[1m]) / rate(hello_response_time_seconds_count[1m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}