apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  # namespace: monitoring
  namespace: monitoring
  annotations:
    sidecar.istio.io/inject: "true"
  labels:
    release: prometheus
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      # - ${namespace}
      - dev
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
