prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: 
      matchLabels:
        release : prometheus
    serviceMonitorNamespaceSelector: {}
    ruleSelector: {}
    ruleNamespaceSelector: {}
    
additionalServiceMonitors:
  - name: node-exporter
    namespace: monitoring
    selector:
      matchLabels:
        app: node-exporter
    endpoints:
      - port: metrics
        interval: 15s
  - name: flask-app-monitor
    namespace: monitoring
    selector:
      matchLabels:
        app: backend 
    endpoints:
      - port: http
        path: /metrics
        interval: 15s

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: prom-operator

prometheusOperator:
  createCustomResource: true
