prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false   
    serviceMonitorNamespaceSelectorUsesHelmValues: false
    storage:
      volumeClaimTemplate:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi  
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

additionalServiceMonitors:
  - name: node-exporter
    namespace: monitoring 
    selector:
      matchLabels:
        app: node-exporter
    endpoints:
      - port: metrics
        interval: 15s
  - name: flask-app-monitor
    namespace: prod 
    labels:
      release: prometheus
    namespaceSelector:
      matchNames:
        - prod
    selector:
      matchLabels:
        app: backend 
    endpoints:
      - port: http
        path: /metrics
        interval: 15s

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: prom-operator
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 1Gi  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheusOperator:
  createCustomResource: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
