prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false   
additionalServiceMonitors:
  - name: node-exporter
    namespace: monitoring 
    selector:
      matchLabels:
        app: node-exporter
    endpoints:
      - port: metrics
        interval: 15s
  - name: flask-app-monitor
    namespace: monitoring
    labels:
      release: prometheus
    namespaceSelector:
      matchNames:
        - prod
    selector:
      matchLabels:
        app: backend 
    endpoints:
      - port: http
        path: /metrics
        interval: 15s

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: prom-operator

prometheusOperator:
  createCustomResource: true
