apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ index .Values.environments .Values.global.environment "replicaCount" }} 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - name : {{ .Values.backend.portname }}
          containerPort: {{ .Values.backend.port }}
        resources: {{- toYaml (index .Values.environments .Values.global.environment "resources") | nindent 12 }}
        envFrom: 
          - configMapRef:
              name: app-config
