{{- if not .Values.backend.versions }}
{{- fail "At least one backend version must be specified in .Values.backend.versions" }}
{{- end }}
{{- $root := . }}
{{- range .Values.backend.versions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-{{ . }}
spec:
  replicas: {{ index $root.Values.environments $root.Values.global.environment "replicaCount" }}
  selector:
    matchLabels:
      app: backend
      version: {{ . }}
  template:
    metadata:
      labels:
        app: backend
        version: {{ . }}
      annotations: {{- toYaml $root.Values.backend.annotations | nindent 8 }}
    spec:
      serviceAccountName: {{ $root.Values.backend.service.accountName }}
      containers:
      - name: backend-{{ . }}
        image: {{ $root.Values.backend.image.repository }}:{{ $root.Values.backend.image.tag }}-{{ . }}
        ports:
        - name: {{ $root.Values.backend.portname }}
          containerPort: {{ $root.Values.backend.port }}
        resources: {{- toYaml (index $root.Values.environments $root.Values.global.environment "resources") | nindent 12 }}
        envFrom:
          - configMapRef:
              name: app-config
{{- end }}
