{{- if not .Values.backend.versions }}
{{- fail "At least one backend version must be specified in .Values.backend.versions" }}
{{- end }}
{{- range .Values.backend.versions }}
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-{{ . }}
spec:
  replicas: {{ index .Values.environments .Values.global.environment "replicaCount" }} 
  selector:
    matchLabels:
      app: backend
      version: {{ . }}
  template:
    metadata:
      labels:
        app: backend
        version: {{ . }}
      annotations: {{- toYaml (index .Values.backend "annotations") | nindent 8 }}
    spec: 
      containers:
      - name: backend-{{ . }}
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}-{{ . }}
        ports:
        - name : {{ .Values.backend.portname }}
          containerPort: {{ .Values.backend.port }}
        resources: {{- toYaml (index .Values.environments .Values.global.environment "resources") | nindent 12 }}
       envFrom: 
        - configMapRef:
           name: app-config
