apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels: 
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: {{ .Values.backend.portname }}
      protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
