{{- if not .Values.backend.versions }}
{{- fail "At least one backend version must be specified in .Values.backend.versions" }}
{{- end }}
{{- $root := . }}
{{- range .Values.backend.versions }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-{{ . }}
  labels: 
    app: frontend
    version: {{ . }}
spec:
  type: {{ $root.Values.frontend.service.type }}
  selector:
    app: frontend
    version: {{ . }}
  ports:
    - protocol: TCP
      port: {{ $root.Values.frontend.port }}
      targetPort: {{ $root.Values.frontend.port }}
{{- end }}
