apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ index .Values.environments .Values.global.environment "replicaCount" }} 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - name : {{ .Values.frontend.portname }} 
          containerPort: {{ .Values.frontend.port }}
        resources: {{- toYaml (index .Values.environments .Values.global.environment "resources") | nindent 12 }}
        envFrom: 
          - configMapRef:
              name: app-config
