{{- if .Values.istio.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
spec:
  host: {{ .Values.istio.destinationRules.frontend.host }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend
spec:
  host: {{ .Values.istio.destinationRules.backend.host }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- end }}
