apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: enable-access
  namespace: prod 
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["istio-system"]
