apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-backend-route 
spec:
  gateways:
  - istio-system/istio-ingress-gateway
  hosts:
  - "*" 
  http:
  - match:
    - uri:
        prefix: /api
    - uri:
        exact: /error
    - uri:
        exact: /users
    - uri:
        exact: /metrics
    route:
    - destination:
        host: backend-service
        subset: v1
        port:
          number: 5000
      weight: 10
    - destination:
        host: backend-service
        subset: v2
        port:
          number: 5000
      weight: 90
    timeout: 1s
    retries:
      attempts: 3
      perTryTimeout: 0.5s
      retryOn: 5xx,gateway-error,connect-failure,refused-stream
  - route:
    - destination:
        host: frontend-service
        port:
          number: 5050
    timeout: 0.5s
