prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: 
      matchLabels:
        release : prometheus
    serviceMonitorNamespaceSelector: {}
    ruleSelector: {}
    ruleNamespaceSelector: {}
    
alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: prom-operator

prometheusOperator:
  createCustomResource: true
