apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: backend  
  endpoints:
  - port: http 
    path: /metrics
    interval: 15s
