global:
  environment: dev

environments:
  dev:
    replicaCount: 2
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  staging:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  prod:
    replicaCount: 1 
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

backend:
  versions:
    - v1
    - v2
  service:
    name: backend-service
  image:
    repository: nebton544/k8s_roadmap
    tag: backend-latest
  replicaCount: 1
  port: 5000
  portname: http
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
  annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
frontend:
  service:
    name: frontend-service
  image:
    repository: nebton544/k8s_roadmap
    tag: frontend-latest
  replicaCount: 1
  port: 5050
  portname: http
  service:
    type: ClusterIP # Used to be NodePort. Cluster IP is for Istio to handle external access  

istio:
  enabled: true
  gateway:
    name: istio-system/istio-ingressgateway
  virtualServices:
    frontend:
      host: "*"
    backend:
      host: backend-service
  destinationRules:
    frontend:
      host: frontend-service
    backend:
      host: backend-service
