name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Level-1/microservices-demo/backend
        push: true
        tags: nebton544/k8s_roadmap:backend-${{ github.sha }}

    - name: Build and push frontend Docker image  
      uses: docker/build-push-action@v2
      with:
        context: ./Level-1/microservices-demo/frontend
        push: true
        tags: nebton544/k8s_roadmap:frontend-${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.30.0'  # Update this to match your cluster version

    - name: Start Minikube
      uses: medyagh/setup-minikube@master

    - name: Deploy to Minikube
      run: |
        cd Level-1/microservices-demo/
        # Update deployment YAML files with new image tags
        sed -i 's|nebton544/k8s_roadmap:backend-.*|nebton544/k8s_roadmap:backend-${{ github.sha }}|' kubernetes/backend-deployment.yaml
        sed -i 's|nebton544/k8s_roadmap:frontend-.*|nebton544/k8s_roadmap:frontend-${{ github.sha }}|' kubernetes/frontend-deployment.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f kubernetes/
        
        # Wait for deployments to be ready
        kubectl rollout status deployment/backend-deployment
        kubectl rollout status deployment/frontend-deployment
        
        # Display deployed services
        kubectl get services
