name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker-practice/actions-setup-docker@master

    - name: Build and push backend Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t backend:${{ github.sha }} ./backend
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push backend:${{ github.sha }}

    - name: Build and push frontend Docker image  
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t frontend:${{ github.sha }} ./frontend
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push frontend:${{ github.sha }}

    - name: Deploy to Minikube
      run: |
        minikube start
        eval $(minikube docker-env)
        kubectl apply -f kubernetes/
